### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by jakezatecky**
Greetings!

This PR updates the various dependencies to their latest versions and slightly modifies `index.js`. In particular, several of the depended packages are quite old and I noticed quite a few `npm audit` warnings related to some of them (related to #19) on a project that depended on this.

This effort is somewhat of a continuation of the work of #15. It promisifies `options.delFn` to work like the newer `del` (without an additional dependency), it updates the tested node versions, it fixes some inconsistencies in formatting (such as some places having spaces AND tabs), and it makes use of `const`/`let` and arrow functions.

The last few items are ultimately unnecessary for this PR but I included them partially because of my lovely editor throwing squiggles everywhere. If you want them removed, I can easily do that and squash the changes to a single commit.

Alternatively, if this remains sitting for a while, I may go ahead and maintain a separate fork (with full credits and a link to this project, naturally) because my compulsiveness wants me to remove those audit errors from the other project.

### CODE REVIEW

**Comment by callumacrae** [comment]
Hey, thanks for the PR!

I've invited you as a collaborator to this repository, because I suck at maintaining it and it's got a bit out of date. I haven't tested your changes (I don't actually use rev-del anymore) but they all look good to me.

Feel free to do whatever and let me know when to publish to npm :)

**Comment by jakezatecky** [comment]
Thanks for the invitation!

I figured that you likely did not use this library anymore, but it's good to see your responsiveness. I still use it on one of the projects I maintain.

The tests all passed on my local machine, but I will get about testing the package on the older project to see if things still work a bit later. I'll let you know!

**Comment by jakezatecky** [comment]
Hey there. I did a quick test to ensure that this build still functions properly with a live project, though naturally it was not fully exhaustive. Everything appears to be working fine.

It should be noted that some of the changes here does mean that the library will no longer work on Node v4. That version fell out of official support last year on 30 April 2018, so I do not know how much of a concern that is. It would probably be considered a breaking change as far as this library goes, though.

I'll leave the decision to you whether or not to merge the changes based on that caveat If that's all fine, I think we would be good for a new release!

**Comment by callumacrae** [comment]
Merged and published as 2.0.0 :)

**Comment by perenstrom** [comment]
Is it possible to link this PR in the release notes? :)

**Comment by callumacrae** [comment]
Done! https://github.com/callumacrae/rev-del/releases/tag/v2.0.0

**Pull request merged**
