### PR TITLE
deleteMapExtensions option defaults to false

### PR DESCRIPTION
**Pull request by joostdekeijzer**
Re #10

### CODE REVIEW

**Comment by callumacrae** [comment]
Ah, I misunderstood what you meant. It was fine before - it's perfectly reasonable to set it to true and this wasn't documenting defaults - but it could use some documentation saying what it actually does.

**Comment by joostdekeijzer** [comment]
Hi @callumacrae,

Anything keeping this PR from being merged? Thanks!

**Comment by callumacrae** [comment]
sorry 🙈 thanks for your PR!

**Comment by joostdekeijzer** [comment]
👍

**Pull request merged**
